### ISSUE TITLE
Error when there is a "/" character in a column gap class

### ISSUE THREAD

**Issue by benface** [hacknug/tailwindcss-multi-column#3]
With this config:
```
theme: {
  columnGap: {
    '1/2': '50%',
  },
},
```

I am getting the following error:
```
🚫 Error: Unexpected '/'. Escaping special characters with \ may help.
at Root._error (./node_modules/postcss-selector-parser/dist/parser.js:160:16)
```

**Comment by hacknug** [comment]
1. I'm dumb and I wasn't escaping the whole modifier 😅
2. This bug affects all my v1.x plugins :tada:
3. Working on a fix now 🛠

**Comment by hacknug** [comment]
@benface just published a new version that should fix the issue. Can you confirm it also works for you?

**Comment by benface** [comment]
@hacknug Yes it works now. Thank you!
